apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-gcp-vm
  title: Create GCP VM
  description: A template to create a VM in Google Cloud Platform using Terraform.
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: user@example.com
