apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: create-gcp-vm
  title: Create GCP VM
  description: A template to create a VM in Google Cloud Platform using Terraform.
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: template
  lifecycle: experimental
  owner: user@example.com
