apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-gcp-vm
  namespace: default
  title: Create GCP VM
  description: A template to create a VM in Google Cloud Platform using Terraform.
spec:
  owner: user@example.com
  type: service

  parameters:
    - title: GCP VM Details
      required:
        - project_id
        - vm_name
        - zone
        - machine_type
      properties:
        project_id:
          title: GCP Project ID
          type: string
          description: The GCP project where the VM will be created.
        vm_name:
          title: VM Name
          type: string
          description: The name of the VM instance.
        zone:
          title: GCP Zone
          type: string
          description: The zone to deploy the VM (e.g., us-central1-a).
        machine_type:
          title: Machine Type
          type: string
          description: The VM type (e.g., e2-medium).

  steps:
    - id: terraform-init
      name: Terraform Init
      action: run:script
      input:
        script: |
          terraform init
        workingDirectory: ./terraform

    - id: terraform-apply
      name: Terraform Apply
      action: run:script
      input:
        script: |
          terraform apply -auto-approve \
            -var="project_id=${{ parameters.project_id }}" \
            -var="vm_name=${{ parameters.vm_name }}" \
            -var="zone=${{ parameters.zone }}" \
            -var="machine_type=${{ parameters.machine_type }}"
        workingDirectory: ./terraform

  output:
    links:
      - title: View VM in GCP
        url: "https://console.cloud.google.com/compute/instances?project=${{ parameters.project_id }}"
